version: "3.9"
services:
  server:
    build:
      context: ./
      target: server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./
      target: frontend
    ports:
      - "4200:80"
